modified:   .github/workflows/vivado_ci.yml modified:   tb/xbar_tb/xbar_tb.sv

diff --git a/.github/workflows/vivado_ci.yml b/.github/workflows/vivado_ci.yml
--- a/.github/workflows/vivado_ci.yml
+++ b/.github/workflows/vivado_ci.yml
@@ -22,4 +22,14 @@ jobs:
       uses: actions/upload-artifact@v4.3.1
       with:
         path: ___CI_REPORT
+
+    - name: Fail if Simulation Contains Fails
+      run: |
+        grep -r "FAIL" ./___CI_REPORT > errors.txt
+        if [[ -s errors.txt ]]; then
+          echo "Simulation Contains Fails"
+          exit 1
+        fi
+      shell: bash
+
       
